### PR TITLE
Add script to automatically enable / disable second monitor (with vnc)

### PR DESCRIPTION
**Pull request by augustin64**
Thanks for this awesome project !
I added a script that I made, which is a bit specific since it's only to use with vnc + adb but is a timesaver.
I used adb in this to prevent exposing vnc to the network (running with `-localhost`), but it could be adapted to run on the network if adb is not installed.

PS: you'll need to enable usb debugging in Android to use adb port forwarding

### CODE REVIEW

**Review by dianariyanto — APPROVED** [review]

**Comment by dianariyanto** [comment]
Hi @augustin64 i think you need edit readme.md too. some user may can't or dont know how to use the script.

**Comment by piranna** [comment]
Any update on this? Can it be merged?

**Comment by augustin64** [comment]
I know it is a bit late, but I've added the instructions for the script.

**Comment by piranna** [comment]
> I know it is a bit late, but I've added the instructions for the script.

No worries, better later than never :-)

**Pull request merged**
